# -*- coding: utf-8 -*-
"""Automatic Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSPU6duv67hqz64r1vmfclMbBuHhfTPr

# **Automatic Translation**

## **Goslate Library**
"""

!pip install goslate

import goslate
inserted_text="python is so powerful"
new_gs=goslate.Goslate()
new_gs.translate(inserted_text, 'es')

"""## **Translate Library**"""

!pip install translate

#Translate text to another language

from translate import Translator
translator=Translator(from_lang="english", to_lang="german")
translation=translator.translate("This is a apple")
print(translation)